#############################################################################
# Makefile for building: UltimateVideoConverter
# Generated by qmake (3.0) (Qt 5.0.0) on: Mon Jan 7 17:58:38 2013
# Project:  UltimateVideoConverter.pro
# Template: subdirs
# Command: /opt/Qt5.0.0/5.0.0/gcc_64/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile UltimateVideoConverter.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /opt/Qt5.0.0/5.0.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-UltimateVideoConverter \
		sub-FFmpegInterface


sub-UltimateVideoConverter-qmake_all:  FORCE
	@test -d UltimateVideoConverter/ || $(MKDIR) UltimateVideoConverter/ 
	cd UltimateVideoConverter/ && $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/UltimateVideoConverter/UltimateVideoConverter.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd UltimateVideoConverter/ && $(MAKE) -f Makefile qmake_all
sub-UltimateVideoConverter: FORCE
	@test -d UltimateVideoConverter/ || $(MKDIR) UltimateVideoConverter/ 
	cd UltimateVideoConverter/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/UltimateVideoConverter/UltimateVideoConverter.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-UltimateVideoConverter-make_first: FORCE
	@test -d UltimateVideoConverter/ || $(MKDIR) UltimateVideoConverter/ 
	cd UltimateVideoConverter/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/UltimateVideoConverter/UltimateVideoConverter.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-UltimateVideoConverter-all: FORCE
	@test -d UltimateVideoConverter/ || $(MKDIR) UltimateVideoConverter/ 
	cd UltimateVideoConverter/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/UltimateVideoConverter/UltimateVideoConverter.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-UltimateVideoConverter-clean: FORCE
	@test -d UltimateVideoConverter/ || $(MKDIR) UltimateVideoConverter/ 
	cd UltimateVideoConverter/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/UltimateVideoConverter/UltimateVideoConverter.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-UltimateVideoConverter-distclean: FORCE
	@test -d UltimateVideoConverter/ || $(MKDIR) UltimateVideoConverter/ 
	cd UltimateVideoConverter/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/UltimateVideoConverter/UltimateVideoConverter.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-UltimateVideoConverter-install_subtargets: FORCE
	@test -d UltimateVideoConverter/ || $(MKDIR) UltimateVideoConverter/ 
	cd UltimateVideoConverter/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/UltimateVideoConverter/UltimateVideoConverter.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-UltimateVideoConverter-uninstall_subtargets: FORCE
	@test -d UltimateVideoConverter/ || $(MKDIR) UltimateVideoConverter/ 
	cd UltimateVideoConverter/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/UltimateVideoConverter/UltimateVideoConverter.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-FFmpegInterface-qmake_all:  FORCE
	@test -d FFmpegInterface/ || $(MKDIR) FFmpegInterface/ 
	cd FFmpegInterface/ && $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/FFmpegInterface/FFmpegInterface.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd FFmpegInterface/ && $(MAKE) -f Makefile qmake_all
sub-FFmpegInterface: FORCE
	@test -d FFmpegInterface/ || $(MKDIR) FFmpegInterface/ 
	cd FFmpegInterface/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/FFmpegInterface/FFmpegInterface.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-FFmpegInterface-make_first: FORCE
	@test -d FFmpegInterface/ || $(MKDIR) FFmpegInterface/ 
	cd FFmpegInterface/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/FFmpegInterface/FFmpegInterface.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-FFmpegInterface-all: FORCE
	@test -d FFmpegInterface/ || $(MKDIR) FFmpegInterface/ 
	cd FFmpegInterface/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/FFmpegInterface/FFmpegInterface.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-FFmpegInterface-clean: FORCE
	@test -d FFmpegInterface/ || $(MKDIR) FFmpegInterface/ 
	cd FFmpegInterface/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/FFmpegInterface/FFmpegInterface.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-FFmpegInterface-distclean: FORCE
	@test -d FFmpegInterface/ || $(MKDIR) FFmpegInterface/ 
	cd FFmpegInterface/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/FFmpegInterface/FFmpegInterface.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-FFmpegInterface-install_subtargets: FORCE
	@test -d FFmpegInterface/ || $(MKDIR) FFmpegInterface/ 
	cd FFmpegInterface/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/FFmpegInterface/FFmpegInterface.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-FFmpegInterface-uninstall_subtargets: FORCE
	@test -d FFmpegInterface/ || $(MKDIR) FFmpegInterface/ 
	cd FFmpegInterface/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/FFmpegInterface/FFmpegInterface.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: UltimateVideoConverter.pro /opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/linux-g++-64/qmake.conf /opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/linux-g++-64/qmake.conf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/debug.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/shared.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/declarative_debug.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/lex.prf \
		UltimateVideoConverter.pro
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile UltimateVideoConverter.pro
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_v8.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/linux-g++-64/qmake.conf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/unix/default_pre.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/debug.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/shared.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/qml_debug.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/declarative_debug.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/wayland-scanner.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.0.0/5.0.0/gcc_64/mkspecs/features/lex.prf:
UltimateVideoConverter.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile UltimateVideoConverter.pro

qmake_all: sub-UltimateVideoConverter-qmake_all sub-FFmpegInterface-qmake_all FORCE

make_first: sub-UltimateVideoConverter-make_first sub-FFmpegInterface-make_first FORCE
all: sub-UltimateVideoConverter-all sub-FFmpegInterface-all FORCE
clean: sub-UltimateVideoConverter-clean sub-FFmpegInterface-clean FORCE
distclean: sub-UltimateVideoConverter-distclean sub-FFmpegInterface-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-UltimateVideoConverter-install_subtargets sub-FFmpegInterface-install_subtargets FORCE
uninstall_subtargets: sub-UltimateVideoConverter-uninstall_subtargets sub-FFmpegInterface-uninstall_subtargets FORCE

sub-UltimateVideoConverter-check:
	@test -d UltimateVideoConverter/ || $(MKDIR) UltimateVideoConverter/ 
	cd UltimateVideoConverter/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/UltimateVideoConverter/UltimateVideoConverter.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-FFmpegInterface-check:
	@test -d FFmpegInterface/ || $(MKDIR) FFmpegInterface/ 
	cd FFmpegInterface/ && ( test -f Makefile || $(QMAKE) /home/lalit/Documents/UltimateVideoConverter/FFmpegInterface/FFmpegInterface.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-UltimateVideoConverter-check sub-FFmpegInterface-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

